=== Bernardo-MG/tabletop-intervals/src/test/resources/parameter/interval.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="test_data">
		<xs:complexType>
			<xs:sequence minOccurs="0" maxOccurs="unbounded">
				<xs:element name="data" type="intervalSimple" />
			</xs:sequence>
		</xs:complexType>
		<xs:unique name="uniqueData">
			<xs:selector xpath="data" />
			<xs:field xpath="interval/lower_limit" />
			<xs:field xpath="interval/upper_limit" />
		</xs:unique>
	</xs:element>

	<xs:complexType name="intervalSimple">
		<xs:all>
			<xs:element name="interval" type="intervalLimits" />
		</xs:all>
		<xs:attribute name="invalid" type="xs:boolean" use="required" />
	</xs:complexType>

	<!-- This should be imported -->

	<xs:complexType name="intervalLimits">
		<xs:annotation>
			<xs:documentation>
				<![CDATA[
					Represents an integer interval.
					It may be proper or not, or even invalid.
				]]>
			</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="lower_limit" type="xs:integer"
				maxOccurs="1" minOccurs="1" />
			<xs:element name="upper_limit" type="xs:integer"
				maxOccurs="1" minOccurs="1" />
		</xs:sequence>
	</xs:complexType>

</xs:schema>

=== Bernardo-MG/tabletop-intervals/src/test/resources/parameter/interval.xml
<?xml version="1.0" encoding="UTF-8"?>
<test_data xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="interval.xsd">
	<!-- ****************************************************************** -->
	<!-- ****************************************************************** -->
	<!-- ************************ BASE TEST VALUES ************************ -->
	<!-- ****************************************************************** -->
	<!-- *********************** POSITIVE INTERVALS *********************** -->
	<!-- ****************************************************************** -->
	<!-- ************************ PROPER INTERVALS ************************ -->
	<!-- Common intervals -->
	<data invalid="false">
		<interval>
			<lower_limit>0</lower_limit>
			<upper_limit>1</upper_limit>
		</interval>
	</data>
	<data invalid="false">
		<interval>
			<lower_limit>0</lower_limit>
			<upper_limit>2</upper_limit>
		</interval>
	</data>
	<data invalid="false">
		<interval>
			<lower_limit>1</lower_limit>
			<upper_limit>2</upper_limit>
		</interval>
	</data>
	<data invalid="false">
		<interval>
			<lower_limit>0</lower_limit>
			<upper_limit>3</upper_limit>
		</interval>
	</data>
	<data invalid="false">
		<interval>
			<lower_limit>1</lower_limit>
			<upper_limit>3</upper_limit>
		</interval>
	</data>
	<data invalid="false">
		<interval>
			<lower_limit>0</lower_limit>
			<upper_limit>4</upper_limit>
		</interval>
	</data>
	<data invalid="false">
		<interval>
			<lower_limit>1</lower_limit>
			<upper_limit>4</upper_limit>
		</interval>
	</data>
	<data invalid="false">
		<interval>
			<lower_limit>0</lower_limit>
			<upper_limit>5</upper_limit>
		</interval>
	</data>
	<data invalid="false">
		<interval>
			<lower_limit>1</lower_limit>
			<upper_limit>5</upper_limit>
		</interval>
	</data>
	<data invalid="false">
		<interval>
			<lower_limit>0</lower_limit>
			<upper_limit>6</upper_limit>
		</interval>
	</data>
	<data invalid="false">
		<interval>
			<lower_limit>1</lower_limit>
			<upper_limit>6</upper_limit>
		</interval>
	</data>
	<data invalid="false">
		<interval>
			<lower_limit>0</lower_limit>
			<upper_limit>8</upper_limit>
		</interval>
	</data>
	<data invalid="false">
		<interval>
			<lower_limit>1</lower_limit>
			<upper_limit>8</upper_limit>
		</interval>
	</data>
	<data invalid="false">
		<interval>
			<lower_limit>0</lower_limit>
			<upper_limit>10</upper_limit>
		</interval>
	</data>
	<data invalid="false">
		<interval>
			<lower_limit>1</lower_limit>
			<upper_limit>10</upper_limit>
		</interval>
	</data>
	<data invalid="false">
		<interval>
			<lower_limit>0</lower_limit>
			<upper_limit>12</upper_limit>
		</interval>
	</data>
	<data invalid="false">
		<interval>
			<lower_limit>1</lower_limit>
			<upper_limit>12</upper_limit>
		</interval>
	</data>
	<data invalid="false">
		<interval>
			<lower_limit>0</lower_limit>
			<upper_limit>20</upper_limit>
		</interval>
	</data>
	<data invalid="false">
		<interval>
			<lower_limit>1</lower_limit>
			<upper_limit>20</upper_limit>
		</interval>
	</data>
	<data invalid="false">
		<interval>
			<lower_limit>0</lower_limit>
			<upper_limit>100</upper_limit>
		</interval>
	</data>
	<data invalid="false">
		<interval>
			<lower_limit>1</lower_limit>
			<upper_limit>100</upper_limit>
		</interval>
	</data>
	<!-- Successions -->
	<data invalid="false">
		<interval>
			<lower_limit>2</lower_limit>
			<upper_limit>3</upper_limit>
		</interval>
	</data>
	<data invalid="false">
		<interval>
			<lower_limit>3</lower_limit>
			<upper_limit>4</upper_limit>
		</interval>
	</data>
	<data invalid="false">
		<interval>
			<lower_limit>4</lower_limit>
			<upper_limit>5</upper_limit>
		</interval>
	</data>
	<data invalid="false">
		<interval>
			<lower_limit>3</lower_limit>
			<upper_limit>10</upper_limit>
		</interval>
	</data>
	<data invalid="false">
		<interval>
			<lower_limit>4</lower_limit>
			<upper_limit>10</upper_limit>
		</interval>
	</data>
	<data invalid="false">
		<interval>
			<lower_limit>5</lower_limit>
			<upper_limit>10</upper_limit>
		</interval>
	</data>
	<!-- Boundary -->
	<data invalid="false">
		<interval>
			<lower_limit>0</lower_limit>
			<upper_limit>2147483646</upper_limit>
		</interval>
	</data>
	<data invalid="false">
		<interval>
			<lower_limit>1</lower_limit>
			<upper_limit>2147483646</upper_limit>
		</interval>
	</data>
	<data invalid="false">
		<interval>
			<lower_limit>100</lower_limit>
			<upper_limit>2147483646</upper_limit>
		</interval>
	</data>
	<!-- ****************************************************************** -->
	<!-- ********************** NOT PROPER INTERVALS ********************** -->
	<data invalid="false">
		<interval>
			<lower_limit>0</lower_limit>
			<upper_limit>0</upper_limit>
		</interval>
	</data>
	<data invalid="false">
		<interval>
			<lower_limit>1</lower_limit>
			<upper_limit>1</upper_limit>
		</interval>
	</data>
	<data invalid="false">
		<interval>
			<lower_limit>2</lower_limit>
			<upper_limit>2</upper_limit>
		</interval>
	</data>
	<data invalid="false">
		<interval>
			<lower_limit>3</lower_limit>
			<upper_limit>3</upper_limit>
		</interval>
	</data>
	<data invalid="false">
		<interval>
			<lower_limit>4</lower_limit>
			<upper_limit>4</upper_limit>
		</interval>
	</data>
	<data invalid="false">
		<interval>
			<lower_limit>6</lower_limit>
			<upper_limit>6</upper_limit>
		</interval>
	</data>
	<data invalid="false">
		<interval>
			<lower_limit>8</lower_limit>
			<upper_limit>8</upper_limit>
		</interval>
	</data>
	<data invalid="false">
		<interval>
			<lower_limit>10</lower_limit>
			<upper_limit>10</upper_limit>
		</interval>
	</data>
	<data invalid="false">
		<interval>
			<lower_limit>12</lower_limit>
			<upper_limit>12</upper_limit>
		</interval>
	</data>
	<data invalid="false">
		<interval>
			<lower_limit>20</lower_limit>
			<upper_limit>20</upper_limit>
		</interval>
	</data>
	<data invalid="false">
		<interval>
			<lower_limit>100</lower_limit>
			<upper_limit>100</upper_limit>
		</interval>
	</data>
	<data invalid="false">
		<interval>
			<lower_limit>2147483646</lower_limit>
			<upper_limit>2147483646</upper_limit>
		</interval>
	</data>
	<!-- ****************************************************************** -->
	<!-- *********************** NEGATIVE INTERVALS *********************** -->
	<!-- ****************************************************************** -->
	<!-- ************************ PROPER INTERVALS ************************ -->
	<data invalid="false">
		<interval>
			<lower_limit>-1</lower_limit>
			<upper_limit>0</upper_limit>
		</interval>
	</data>
	<data invalid="false">
		<interval>
			<lower_limit>-2</lower_limit>
			<upper_limit>-1</upper_limit>
		</interval>
	</data>
	<data invalid="false">
		<interval>
			<lower_limit>-3</lower_limit>
			<upper_limit>-2</upper_limit>
		</interval>
	</data>
	<data invalid="false">
		<interval>
			<lower_limit>-4</lower_limit>
			<upper_limit>-3</upper_limit>
		</interval>
	</data>
	<data invalid="false">
		<interval>
			<lower_limit>-5</lower_limit>
			<upper_limit>-4</upper_limit>
		</interval>
	</data>
	<data invalid="false">
		<interval>
			<lower_limit>-10</lower_limit>
			<upper_limit>0</upper_limit>
		</interval>
	</data>
	<data invalid="false">
		<interval>
			<lower_limit>-10</lower_limit>
			<upper_limit>-1</upper_limit>
		</interval>
	</data>
	<data invalid="false">
		<interval>
			<lower_limit>-10</lower_limit>
			<upper_limit>-2</upper_limit>
		</interval>
	</data>
	<data invalid="false">
		<interval>
			<lower_limit>-10</lower_limit>
			<upper_limit>-4</upper_limit>
		</interval>
	</data>
	<data invalid="false">
		<interval>
			<lower_limit>-10</lower_limit>
			<upper_limit>-5</upper_limit>
		</interval>
	</data>
	<data invalid="false">
		<interval>
			<lower_limit>-2147483648</lower_limit>
			<upper_limit>0</upper_limit>
		</interval>
	</data>
	<data invalid="false">
		<interval>
			<lower_limit>-2147483648</lower_limit>
			<upper_limit>-1</upper_limit>
		</interval>
	</data>
	<data invalid="false">
		<interval>
			<lower_limit>-2147483648</lower_limit>
			<upper_limit>-100</upper_limit>
		</interval>
	</data>
	<!-- ****************************************************************** -->
	<!-- ********************** NOT PROPER INTERVALS ********************** -->
	<data invalid="false">
		<interval>
			<lower_limit>-1</lower_limit>
			<upper_limit>-1</upper_limit>
		</interval>
	</data>
	<data invalid="false">
		<interval>
			<lower_limit>-2</lower_limit>
			<upper_limit>-2</upper_limit>
		</interval>
	</data>
	<data invalid="false">
		<interval>
			<lower_limit>-3</lower_limit>
			<upper_limit>-3</upper_limit>
		</interval>
	</data>
	<data invalid="false">
		<interval>
			<lower_limit>-10</lower_limit>
			<upper_limit>-10</upper_limit>
		</interval>
	</data>
	<data invalid="false">
		<interval>
			<lower_limit>-100</lower_limit>
			<upper_limit>-100</upper_limit>
		</interval>
	</data>
	<data invalid="false">
		<interval>
			<lower_limit>-2147483648</lower_limit>
			<upper_limit>-2147483648</upper_limit>
		</interval>
	</data>
	<!-- ****************************************************************** -->
	<!-- ********************** BOTH SIDES INTERVALS ********************** -->
	<!-- ****************************************************************** -->
	<!-- ************************ PROPER INTERVALS ************************ -->
	<data invalid="false">
		<interval>
			<lower_limit>-1</lower_limit>
			<upper_limit>1</upper_limit>
		</interval>
	</data>
	<data invalid="false">
		<interval>
			<lower_limit>-1</lower_limit>
			<upper_limit>10</upper_limit>
		</interval>
	</data>
	<data invalid="false">
		<interval>
			<lower_limit>-10</lower_limit>
			<upper_limit>1</upper_limit>
		</interval>
	</data>
	<data invalid="false">
		<interval>
			<lower_limit>-5</lower_limit>
			<upper_limit>10</upper_limit>
		</interval>
	</data>
	<data invalid="false">
		<interval>
			<lower_limit>-10</lower_limit>
