=== Bernardo-MG/tabletop-intervals/src/test/resources/parameter/interval-containing-value.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="test_data">
		<xs:complexType>
			<xs:sequence minOccurs="0" maxOccurs="unbounded">
				<xs:element name="data" type="intervalAndValue" />
			</xs:sequence>
		</xs:complexType>
		<xs:unique name="uniqueData">
			<xs:selector xpath="data" />
			<xs:field xpath="interval/lower_limit" />
			<xs:field xpath="interval/upper_limit" />
			<xs:field xpath="value" />
		</xs:unique>
	</xs:element>

	<xs:complexType name="intervalAndValue">
		<xs:annotation>
			<xs:documentation>
				<![CDATA[
					Represents an integer interval with a value.
					The value may or may not be contained, this should be
					indicated on the attribute.
				]]>
			</xs:documentation>
		</xs:annotation>
		<xs:all>
			<xs:element name="interval" type="intervalLimits" />
			<xs:element name="value" type="xs:int" />
		</xs:all>
		<xs:attribute name="contained" type="xs:boolean" use="required" />
	</xs:complexType>

	<xs:complexType name="intervalLimits">
		<xs:annotation>
			<xs:documentation>
				<![CDATA[
					Represents an integer interval.
					It may be proper or not, or even invalid.
				]]>
			</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="lower_limit" type="xs:integer"
				maxOccurs="1" minOccurs="1" />
			<xs:element name="upper_limit" type="xs:integer"
				maxOccurs="1" minOccurs="1" />
		</xs:sequence>
	</xs:complexType>

</xs:schema>

=== Bernardo-MG/tabletop-intervals/src/test/resources/parameter/interval-containing-value.xml
<?xml version="1.0" encoding="UTF-8"?>
<test_data xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="interval-containing-value.xsd">
	<!-- ****************************************************************** -->
	<!-- ****************************************************************** -->
	<!-- ********************* PROPER INTERVAL VALUES ********************* -->
	<!-- ****************************************************************** -->
	<!-- ************************ CONTAINED VALUES ************************ -->
	<!-- ****************************************************************** -->
	<!-- ************************ POSITIVE INTERVAL *********************** -->
	<!-- Interval 0 to 1 -->
	<data contained="true">
		<interval>
			<lower_limit>0</lower_limit>
			<upper_limit>1</upper_limit>
		</interval>
		<value>0</value>
	</data>
	<data contained="true">
		<interval>
			<lower_limit>0</lower_limit>
			<upper_limit>1</upper_limit>
		</interval>
		<value>1</value>
	</data>
	<!-- Interval 1 to 2 -->
	<data contained="true">
		<interval>
			<lower_limit>1</lower_limit>
			<upper_limit>2</upper_limit>
		</interval>
		<value>1</value>
	</data>
	<data contained="true">
		<interval>
			<lower_limit>1</lower_limit>
			<upper_limit>2</upper_limit>
		</interval>
		<value>2</value>
	</data>
	<!-- Interval 0 to 10 -->
	<data contained="true">
		<interval>
			<lower_limit>0</lower_limit>
			<upper_limit>10</upper_limit>
		</interval>
		<value>0</value>
	</data>
	<data contained="true">
		<interval>
			<lower_limit>0</lower_limit>
			<upper_limit>10</upper_limit>
		</interval>
		<value>1</value>
	</data>
	<data contained="true">
		<interval>
			<lower_limit>0</lower_limit>
			<upper_limit>10</upper_limit>
		</interval>
		<value>2</value>
	</data>
	<data contained="true">
		<interval>
			<lower_limit>0</lower_limit>
			<upper_limit>10</upper_limit>
		</interval>
		<value>3</value>
	</data>
	<data contained="true">
		<interval>
			<lower_limit>0</lower_limit>
			<upper_limit>10</upper_limit>
		</interval>
		<value>4</value>
	</data>
	<data contained="true">
		<interval>
			<lower_limit>0</lower_limit>
			<upper_limit>10</upper_limit>
		</interval>
		<value>5</value>
	</data>
	<data contained="true">
		<interval>
			<lower_limit>0</lower_limit>
			<upper_limit>10</upper_limit>
		</interval>
		<value>6</value>
	</data>
	<data contained="true">
		<interval>
			<lower_limit>0</lower_limit>
			<upper_limit>10</upper_limit>
		</interval>
		<value>7</value>
	</data>
	<data contained="true">
		<interval>
			<lower_limit>0</lower_limit>
			<upper_limit>10</upper_limit>
		</interval>
		<value>8</value>
	</data>
	<data contained="true">
		<interval>
			<lower_limit>0</lower_limit>
			<upper_limit>10</upper_limit>
		</interval>
		<value>9</value>
	</data>
	<data contained="true">
		<interval>
			<lower_limit>0</lower_limit>
			<upper_limit>10</upper_limit>
		</interval>
		<value>10</value>
	</data>
	<!-- Interval 1 to 10 -->
	<data contained="true">
		<interval>
			<lower_limit>1</lower_limit>
			<upper_limit>10</upper_limit>
		</interval>
		<value>1</value>
	</data>
	<data contained="true">
		<interval>
			<lower_limit>1</lower_limit>
			<upper_limit>10</upper_limit>
		</interval>
		<value>2</value>
	</data>
	<data contained="true">
		<interval>
			<lower_limit>1</lower_limit>
			<upper_limit>10</upper_limit>
		</interval>
		<value>3</value>
	</data>
	<data contained="true">
		<interval>
			<lower_limit>1</lower_limit>
			<upper_limit>10</upper_limit>
		</interval>
		<value>4</value>
	</data>
	<data contained="true">
		<interval>
			<lower_limit>1</lower_limit>
			<upper_limit>10</upper_limit>
		</interval>
		<value>5</value>
	</data>
	<data contained="true">
		<interval>
			<lower_limit>1</lower_limit>
			<upper_limit>10</upper_limit>
		</interval>
		<value>6</value>
	</data>
	<data contained="true">
		<interval>
			<lower_limit>1</lower_limit>
			<upper_limit>10</upper_limit>
		</interval>
		<value>7</value>
	</data>
	<data contained="true">
		<interval>
			<lower_limit>1</lower_limit>
			<upper_limit>10</upper_limit>
		</interval>
		<value>8</value>
	</data>
	<data contained="true">
		<interval>
			<lower_limit>1</lower_limit>
			<upper_limit>10</upper_limit>
		</interval>
		<value>9</value>
	</data>
	<data contained="true">
		<interval>
			<lower_limit>1</lower_limit>
			<upper_limit>10</upper_limit>
		</interval>
		<value>10</value>
	</data>
	<!-- Interval 0 to 100 -->
	<data contained="true">
		<interval>
			<lower_limit>0</lower_limit>
			<upper_limit>100</upper_limit>
		</interval>
		<value>0</value>
	</data>
	<data contained="true">
		<interval>
			<lower_limit>0</lower_limit>
			<upper_limit>100</upper_limit>
		</interval>
		<value>1</value>
	</data>
	<data contained="true">
		<interval>
			<lower_limit>0</lower_limit>
			<upper_limit>100</upper_limit>
		</interval>
		<value>2</value>
	</data>
	<data contained="true">
		<interval>
			<lower_limit>0</lower_limit>
			<upper_limit>100</upper_limit>
		</interval>
		<value>29</value>
	</data>
	<data contained="true">
		<interval>
			<lower_limit>0</lower_limit>
			<upper_limit>100</upper_limit>
		</interval>
		<value>30</value>
	</data>
	<data contained="true">
		<interval>
			<lower_limit>0</lower_limit>
			<upper_limit>100</upper_limit>
		</interval>
		<value>31</value>
	</data>
	<data contained="true">
		<interval>
			<lower_limit>0</lower_limit>
			<upper_limit>100</upper_limit>
		</interval>
		<value>99</value>
	</data>
	<data contained="true">
		<interval>
			<lower_limit>0</lower_limit>
			<upper_limit>100</upper_limit>
		</interval>
		<value>100</value>
	</data>
	<!-- Interval 1 to 100 -->
	<data contained="true">
		<interval>
			<lower_limit>1</lower_limit>
			<upper_limit>100</upper_limit>
		</interval>
		<value>1</value>
	</data>
	<data contained="true">
		<interval>
			<lower_limit>1</lower_limit>
			<upper_limit>100</upper_limit>
		</interval>
		<value>29</value>
	</data>
	<data contained="true">
		<interval>
			<lower_limit>1</lower_limit>
			<upper_limit>100</upper_limit>
		</interval>
		<value>30</value>
	</data>
	<data contained="true">
		<interval>
			<lower_limit>1</lower_limit>
			<upper_limit>100</upper_limit>
		</interval>
		<value>31</value>
	</data>
	<data contained="true">
		<interval>
			<lower_limit>1</lower_limit>
			<upper_limit>100</upper_limit>
		</interval>
		<value>99</value>
	</data>
	<data contained="true">
		<interval>
			<lower_limit>1</lower_limit>
			<upper_limit>100</upper_limit>
		</interval>
		<value>100</value>
	</data>
	<!-- Interval 0 to MAX -->
	<data contained="true">
		<interval>
			<lower_limit>0</lower_limit>
			<upper_limit>2147483647</upper_limit>
		</interval>
		<value>0</value>
	</data>
	<data contained="true">
		<interval>
			<lower_limit>0</lower_limit>
			<upper_limit>2147483647</upper_limit>
		</interval>
		<value>1</value>
	</data>
	<data contained="true">
		<interval>
			<lower_limit>0</lower_limit>
			<upper_limit>2147483647</upper_limit>
		</interval>
		<value>2</value>
	</data>
	<data contained="true">
		<interval>
			<lower_limit>0</lower_limit>
			<upper_limit>2147483647</upper_limit>
		</interval>
		<value>3</value>
	</data>
	<data contained="true">
		<interval>
			<lower_limit>0</lower_limit>
			<upper_limit>2147483647</upper_limit>
		</interval>
		<value>2147483644</value>
	</data>
	<data contained="true">
		<interval>
			<lower_limit>0</lower_limit>
			<upper_limit>2147483647</upper_limit>
		</interval>
		<value>2147483645</value>
	</data>
	<data contained="true">
		<interval>
			<lower_limit>0</lower_limit>
			<upper_limit>2147483647</upper_limit>
		</interval>
		<value>2147483646</value>
	</data>
	<data contained="true">
		<interval>
			<lower_limit>0</lower_limit>
			<upper_limit>2147483647</upper_limit>
		</interval>
		<value>2147483647</value>
	</data>
	<!-- Interval 1 to MAX -->
	<data contained="true">
		<interval>
			<lower_limit>1</lower_limit>
			<upper_limit>2147483647</upper_limit>
		</interval>
		<value>1</value>
	</data>
	<data contained="true">
		<interval>
			<lower_limit>1</lower_limit>
			<upper_limit>2147483647</upper_limit>
		</interval>
		<value>2</value>
	</data>
	<data contained="true">
		<interval>
			<lower_limit>1</lower_limit>
			<upper_limit>2147483647</upper_limit>
		</interval>
		<value>3</value>
	</data>
	<data contained="true">
		<interval>
			<lower_limit>1</lower_limit>
			<upper_limit>2147483647</upper_limit>
		</interval>
		<value>4</value>
	</data>
	<data contained="true">
		<interval>
			<lower_limit>1</lower_limit>
			<upper_limit>2147483647</upper_limit>
		</interval>
		<value>2147483644</value>
	</data>
	<data contained="true">
		<interval>
			<lower_limit>1</lower_limit>
			<upper_limit>2147483647</upper_limit>
		</interval>
		<value>2147483645</value>
	</data>
	<data contained="true">
		<interval>
			<lower_limit>1</lower_limit>
			<upper_limit>2147483647</upper_limit>
		</interval>
		<value>2147483646</value>
	</data>
	<data contained="true">
		<interval>
			<lower_limit>1</lower_limit>
			<upper_limit>2147483647</upper_limit>
		</interval>
		<value>2147483647</value>
	</data>
	<!-- Interval 100 to MAX -->
	<data contained="true">
		<interval>
			<lower_limit>100</lower_limit>
			<upper_limit>2147483647</upper_limit>
		</interval>
		<value>100</value>
	</data>
	<data contained="true">
		<interval>
			<lower_limit>100</lower_limit>
			<upper_limit>2147483647</upper_limit>
		</interval>
		<value>101</value>
	</data>
	<data contained="true">
		<interval>
			<lower_limit>100</lower_limit>
			<upper_limit>2147483647</upper_limit>
		</interval>
		<value>102</value>
	</data>
	<data contained="true">
		<interval>
			<lower_limit>100</lower_limit>
			<upper_limit>2147483647</upper_limit>
		</interval>
		<value>103</value>
	</data>
	<data contained="true">
		<interval>
			<lower_limit>100</lower_limit>
			<upper_limit>2147483647</upper_limit>
		</interval>
		<value>104</value>
	</data>
	<data contained="true">
		<interval>
